{"Properties":[],"Name":"","Children":[{"Properties":[
    {"Name":"rowCount","Value":1},
    {"Name":"columnCount","Value":3},
    {"Name":"0-1-name","Value":"playerID"},
    {"Name":"0-1-type","Value":1},
    {"Name":"0-2-name","Value":"playerName"},
    {"Name":"0-2-type","Value":1},
    {"Name":"0-3-name","Value":"playerstats"},
    {"Name":"0-3-type","Value":2}],
    {"Name":"id911451_headers","Children":[]},
    {"Properties":[
        {"Name":"","Value":"|1|Jonathan|123|"},{"Name":"","Value":"|2|Carli|321|"}],
        {"Name":"id911451","Children":[]}]}